name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the tag name
        id: get_tag_name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
      - name: Build 
        run: |
          echo '{"version":"${{ env.TAG_NAME }}"}' > templates/metadata.json;
          bazel build //:axe --config=release;
          cp bazel-bin/axe axe;
          chmod +x axe;

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ env.TAG_NAME }} \
            --title "Release ${{ env.TAG_NAME }}" \
            --generate-notes \
            --draft=false \
            --prerelease=false

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ env.TAG_NAME }} axe
